# Generated by Django 4.2 on 2026-01-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_media/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='artist_media/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Customer.artistprofile')),
            ],
        ),
    ]
