# Generated by Django 4.2 on 2026-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_artistmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist/profile/'),
        ),
    ]
