# Generated by Django 4.2 on 2026-01-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_artistprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='profile_image',
        ),
    ]
