# Generated by Django 4.2 on 2026-01-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_remove_artistprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmedia',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='artistmedia',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.artistprofile'),
        ),
        migrations.AlterField(
            model_name='artistmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_media/'),
        ),
        migrations.AlterField(
            model_name='artistmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='artist_media/'),
        ),
    ]
