# Generated by Django 4.2 on 2025-12-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Notes_Data')),
                ('desc', models.TextField()),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.noteinfo')),
            ],
        ),
    ]
