# Generated by Django 4.2 on 2026-01-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0002_alter_artistprofile_bio_alter_artistprofile_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='artist_media/')),
                ('media_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Artist.artistprofile')),
            ],
        ),
    ]
