# Generated by Django 4.2 on 2026-01-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0003_artistmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmedia',
            name='file',
        ),
        migrations.RemoveField(
            model_name='artistmedia',
            name='media_type',
        ),
        migrations.AddField(
            model_name='artistmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_media/images/'),
        ),
        migrations.AddField(
            model_name='artistmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='artist_media/videos/'),
        ),
        migrations.AlterField(
            model_name='artistmedia',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.artistprofile'),
        ),
    ]
